---
- name: Update and secure LXC containers
  hosts: lxc_containers
  become: yes
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install security updates
      ansible.builtin.apt:
        upgrade: dist
        only_upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
        autoclean: yes

    - name: Ensure all security patches are installed
      ansible.builtin.command:
        cmd: unattended-upgrade -d
        creates: /var/log/unattended-upgrades/unattended-upgrades.log
      ignore_errors: yes

    - name: Reboot the container if updates require it
      ansible.builtin.reboot:
        reboot_timeout: 600
        test_command: uptime
      when: ansible_facts['pkg_mgr'] == "apt"
      register: reboot_result
      ignore_errors: yes

    - name: Verify that the container is back online after reboot
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
      when: reboot_result is changed
      register: container_up

    - name: Check installed packages versions
      ansible.builtin.shell: dpkg-query -l | grep -i "version"
      register: installed_packages
      changed_when: false

    - name: Show updated package list
      debug:
        msg: "{{ installed_packages.stdout_lines }}"
